### ISSUE TITLE
stac-fastapi deleting and recreating collection causes item insert errors

### ISSUE THREAD

**Issue by sylar11** [stac-utils/stac-fastapi#597]
Hi all,
I use to create my collections by means of the API stac-fastapi. Unfortunately, if I have to delete one of them and recreate it with the same ID I can't load items anymore. I'm using the command: _pypgstac load items_ 
I always get the following error when uploading the item using the command:

_psycopg.errors.UndefinedTable: relation "_items_3" does not exist_

To be able to upload items again I have to empty my DB and then I can complete the process.

Is there any workaround or bug fix for this?

**Comment by mmcfarland** [comment]
This was a bug in pgstac that was resolved in 0.7.10, see the related issue https://github.com/stac-utils/pgstac/issues/185

**Comment by gadomski** [comment]
Closing as fixed-in-upstream, @sylar11 if you update to v0.7.10 hopefully that fixes your problem. If you update and it _doesn't_ fix, please re-open. Thanks @mmcfarland.

**Comment by mmcfarland** [comment]
Can you confirm the pgstac migration version? I'm not sure if the pypgstac version you reported is just for the Python library, which may or may not be the same as your current pgstac migration version. You have two methods to check the database version:

`pypgstac version --dsn ${DSN}`

or if you're already in the DB

`select * from pgstac.migrations;` and check the latest value.

Additionally, in [this comment](https://github.com/stac-utils/pgstac/issues/185#issuecomment-1591815599) it's noted that the issue is fixed on _new_ versions of 0.7.10, but if a collection is in a bad state already (even after the pgstac fix is applied), there are few manual cleanup steps recommend.

**Comment by sylar11** [comment]
Hi all,
I did a better check of the version I have using the cmd 

`pypgstac version --dsn ${DSN}`

Actually, I got: 0.7.9. 
Sorry for the misunderstanding!

The problem is that I'm using a docker to have the API. 
Is there a way to correctly upgrade the version? I'm running the stac fastAPI using the docker I downloaded here: [https://github.com/stac-utils/stac-fastapi-pgstac](url)

but I installed pypgstac using pip installer. In fact running the command `pip list` I got 0.7.10

**Comment by gadomski** [comment]
The **stac-fastapi-pgstac** version is independent from the **pgstac** version. Make sure you're referencing the correct version of https://github.com/stac-utils/pgstac, e.g.

```docker
FROM ghcr.io/stac-utils/pgstac:v0.7.10
```

If you used the `docker-compose.yml` from **stac-fastapi-pgstac**, it still happens to be on v0.7.9: https://github.com/stac-utils/stac-fastapi-pgstac/blob/9692f1e402d9b23eec8e628badef6cc43f2e606f/docker-compose.yml#L36. In your own `docker-compose.yml`, you can just bump that version to v0.7.10.

**Comment by sylar11** [comment]
@gadomski thanks for your suggestion. 

I could upgrade the pypgstac version and now I can delete and recreate the collections without any errors. :)
